cargo-features = ["profile-rustflags"]

[package]
name = "lychrel_base10_simd"
version = "0.1.0"
edition = "2024"

[dependencies]
affinity = "0.1.2"
# rayon = "1.10.0"


[profile.release]
opt-level = 3
debug = true
debug-assertions=false
overflow-checks = false
panic = "abort"
codegen-units = 1
rustflags = ["-C", "target-cpu=native", "-Z", "threads=32", "-C", "embed-bitcode", "-C", "force-frame-pointers=yes"]
lto = "fat"

[profile.release.package."*"]
opt-level = 3
debug = true
overflow-checks = false
codegen-units = 1
rustflags = ["-C", "target-cpu=native", "-Z", "threads=32", "-C", "embed-bitcode", "-C", "force-frame-pointers=yes"]

[profile.release.build-override]
opt-level = 3
debug = true
overflow-checks = false
codegen-units = 1
rustflags = ["-C", "target-cpu=native", "-Z", "threads=32", "-C", "embed-bitcode", "-C", "force-frame-pointers=yes"]

[profile.test]
inherits = "dev"
rustflags = ["-C", "target-cpu=native"]
