cargo-features = ["profile-rustflags", "panic-immediate-abort"]

[package]
name = "lychrel_base10_simd"
version = "0.1.0"
edition = "2024"
default-run = "lychrel_base10_simd"

[features]
no-verify = []
no-avx = []
64-byte-limbs = []
1g-pages = []
global-alloc = []
no-prefetch = []
no-stream = ["no-prefetch"]

[target.'cfg(target_family = "windows")'.dependencies]
windows = { version = "0", features = [
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_Security",
    "Win32_System_Console",
] }
memory-stats = "1.2"

[target.'cfg(target_family = "unix")'.dependencies]
libc = { git = "https://github.com/rust-lang/libc.git", branch = "main", features = ["extra_traits"] }

[dev-dependencies]
rand = "0.9"

[target.'cfg(target_family = "windows")'.build-dependencies]
embed-resource = "3"

[profile.release]
strip = true
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
codegen-units = 1
lto = "fat"
panic = "abort"
rustflags = ["-Z", "fmt-debug=none", "-C", "target-cpu=native"]

[profile.release.build-override]
strip = true
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
codegen-units = 1
rustflags = ["-Z", "fmt-debug=none", "-C", "target-cpu=native"]

[profile.profiling]
inherits = "release"
strip = false
debug = true
rustflags = ["-Z", "fmt-debug=none", "-C", "force-frame-pointers=yes", "-C", "target-cpu=native"]

[profile.profiling.build-override]
inherits = "release"
strip = false
debug = true
rustflags = ["-Z", "fmt-debug=none", "-C", "force-frame-pointers=yes", "-C", "target-cpu=native"]

[profile.dev]
opt-level = 1
debug = true
overflow-checks = true
debug-assertions = true
lto = false
rustflags = ["-C", "force-frame-pointers=yes"]


[profile.test]
inherits = "dev"
opt-level = 1
overflow-checks = true
debug-assertions = true
lto = false
rustflags = ["-C", "force-frame-pointers=yes"]
