#![feature(portable_simd)]
#![feature(const_convert)]
#![feature(const_trait_impl)]
#![feature(likely_unlikely)]
#![feature(cold_path)]
#![feature(slice_from_ptr_range)]
#![feature(int_roundings)]
#![feature(const_cmp)]
#![feature(const_eval_select)]
#![feature(core_intrinsics)]
#![allow(internal_features)]
#![feature(iter_collect_into)]
#![feature(cfg_overflow_checks)]
#![feature(const_default)]
#![feature(const_clone)]
#![feature(const_precise_live_drops)]
#![feature(const_index)]
#![feature(allocator_api)]
#![feature(alloc_layout_extra)]
#![deny(clippy::all)]

pub mod integer_limb;
