#![feature(portable_simd)]
#![feature(const_from)]
#![feature(const_trait_impl)]
#![feature(likely_unlikely)]
#![feature(cold_path)]
#![feature(slice_from_ptr_range)]
#![feature(int_roundings)]
#![feature(const_cmp)]
#![feature(const_eval_select)]
#![feature(core_intrinsics)]
#![allow(internal_features)]
#![feature(iter_collect_into)]
#![deny(clippy::all)]

pub mod integer_limb;
